name: CI Build for Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sign in to Droplet and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |

            cd /home/LOOOP__BACKEND

            docker stop looop-backend || true
            docker rm looop-backend || true

            docker rmi looop-backend || true

            git pull origin main

            docker build -t looop-backend .

            docker run -d --name looop-backend -p 4000:3000 \
              --env LOOOP_CONTRACT=${{ secrets.LOOOP_CONTRACT }} \
              --env PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
              --env PROVIDER=${{ secrets.PROVIDER }} \
              --env ACCT_ADDRESS=${{ secrets.ACCT_ADDRESS }} \
              --env NFT_CONTRACT_ADDRESS=${{ secrets.NFT_CONTRACT_ADDRESS }} \
              --env NFT_TOKEN_ID=${{ secrets.NFT_TOKEN_ID }} \
              --env IMPLEMENTATION_HASH=${{ secrets.IMPLEMENTATION_HASH }} \
              --env DWT_SECRET=${{ secrets.DWT_SECRET }} \
              --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --env MONGODB_URI=${{ secrets.MONGODB_URI }} \
              --env XION_BASE_URL=${{ secrets.XION_BASE_URL }} \
              --env FLW_PUBLIC_KEY=${{ secrets.FLW_PUBLIC_KEY }} \
              --env FLW_SECRET_KEY=${{ secrets.FLW_SECRET_KEY }} \
              --env ADMIN_MNEMONIC=${{ secrets.ADMIN_MNEMONIC }} \
              --env SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
              --env SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
              --env EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} \
              --env EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
              --env PAYAZA_SECRET_KEY=${{ secrets.PAYAZA_SECRET_KEY }} \
              --env HOSTINGER_EMAIL=${{ secrets.HOSTINGER_EMAIL }} \
              --env HOSTINGER_PASSWORD=${{ secrets.HOSTINGER_PASSWORD }} \
              --env REWARD_NEW_USER_SIGNUP=${{ secrets.REWARD_NEW_USER_SIGNUP }} \
              --env REWARD_PURCHASE=${{ secrets.REWARD_PURCHASE }} \
              --env REWARD_PROFILE_COMPLETION=${{ secrets.REWARD_PROFILE_COMPLETION }} \
              --env REWARD_SOCIAL_SHARE=${{ secrets.REWARD_SOCIAL_SHARE }} \
              --env SERVER_SECRET=${{ secrets.SERVER_SECRET }} \
              --env RPC_URL=${{ secrets.RPC_URL }} \
              --env REST_URL=${{ secrets.REST_URL }} \
              --env GRANTER_ADDRESS=${{ secrets.GRANTER_ADDRESS }} \
              --env GRANTER_MNEMONIC=${{ secrets.GRANTER_MNEMONIC }} \
              --env WALLET_API_BASE_URL=${{ secrets.WALLET_API_BASE_URL }} \
              --env PIXABAY_API_KEY=${{ secrets.PIXABAY_API_KEY }} \
              looop-backend
